name: Young Style 
title: Young Style | Dress 2 Impress
description: Tinute pentru stilul tau.
tags:
  - fashion
  - style
  - young
email: contact@youngstyle.ro
disqus_username: disqus_username
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
